<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="28" started-at="2018-10-15T06:47:00Z" finished-at="2018-10-15T06:47:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="28" started-at="2018-10-15T06:47:00Z" finished-at="2018-10-15T06:47:00Z">
      <class name="testng1.NewTest1">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testng1.NewTest1@305cc7a5]" name="beforeClass" is-config="true" duration-ms="8" started-at="2018-10-15T14:47:00Z" finished-at="2018-10-15T14:47:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="f(java.lang.Integer, java.lang.String)[pri:0, instance:testng1.NewTest1@305cc7a5]" name="f" duration-ms="0" started-at="2018-10-15T14:47:00Z" data-provider="dp" finished-at="2018-10-15T14:47:00Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void testng1.NewTest1.f(java.lang.Integer,java.lang.String) requires a @DataProvider named : dp]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void testng1.NewTest1.f(java.lang.Integer,java.lang.String) requires a @DataProvider named : dp
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:testng1.NewTest1@305cc7a5]" name="afterClass" is-config="true" duration-ms="0" started-at="2018-10-15T14:47:00Z" finished-at="2018-10-15T14:47:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- testng1.NewTest1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
